/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rocproject_roc_log_LogLevel */

#ifndef _Included_com_rocproject_roc_log_LogLevel
#define _Included_com_rocproject_roc_log_LogLevel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rocproject_roc_log_LogLevel
 * Method:    getRocLogNone
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rocproject_roc_log_LogLevel_getRocLogNone
  (JNIEnv *, jclass);

/*
 * Class:     com_rocproject_roc_log_LogLevel
 * Method:    getRocLogError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rocproject_roc_log_LogLevel_getRocLogError
  (JNIEnv *, jclass);

/*
 * Class:     com_rocproject_roc_log_LogLevel
 * Method:    getRocLogInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rocproject_roc_log_LogLevel_getRocLogInfo
  (JNIEnv *, jclass);

/*
 * Class:     com_rocproject_roc_log_LogLevel
 * Method:    getRocLogDebug
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rocproject_roc_log_LogLevel_getRocLogDebug
  (JNIEnv *, jclass);

/*
 * Class:     com_rocproject_roc_log_LogLevel
 * Method:    getRocLogTrace
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rocproject_roc_log_LogLevel_getRocLogTrace
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
