/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rocproject_roc_context_Context */

#ifndef _Included_com_rocproject_roc_context_Context
#define _Included_com_rocproject_roc_context_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rocproject_roc_context_Context
 * Method:    rocContextOpen
 * Signature: (Lcom/rocproject/roc/config/ContextConfig;)V
 */
JNIEXPORT void JNICALL Java_com_rocproject_roc_context_Context_rocContextOpen
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_rocproject_roc_context_Context
 * Method:    rocContextClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rocproject_roc_context_Context_rocContextClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
