/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rocproject_roc_address_Family */

#ifndef _Included_com_rocproject_roc_address_Family
#define _Included_com_rocproject_roc_address_Family
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rocproject_roc_address_Family
 * Method:    getRocAFInvalid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rocproject_roc_address_Family_getRocAFInvalid
  (JNIEnv *, jclass);

/*
 * Class:     com_rocproject_roc_address_Family
 * Method:    getRocAFAuto
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rocproject_roc_address_Family_getRocAFAuto
  (JNIEnv *, jclass);

/*
 * Class:     com_rocproject_roc_address_Family
 * Method:    getRocAFIPv4
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rocproject_roc_address_Family_getRocAFIPv4
  (JNIEnv *, jclass);

/*
 * Class:     com_rocproject_roc_address_Family
 * Method:    getRocAFIPv6
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rocproject_roc_address_Family_getRocAFIPv6
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
