/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rocproject_roc_config_ResamplerProfile */

#ifndef _Included_com_rocproject_roc_config_ResamplerProfile
#define _Included_com_rocproject_roc_config_ResamplerProfile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rocproject_roc_config_ResamplerProfile
 * Method:    getRocResamplerDisable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rocproject_roc_config_ResamplerProfile_getRocResamplerDisable
  (JNIEnv *, jclass);

/*
 * Class:     com_rocproject_roc_config_ResamplerProfile
 * Method:    getRocResamplerDefault
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rocproject_roc_config_ResamplerProfile_getRocResamplerDefault
  (JNIEnv *, jclass);

/*
 * Class:     com_rocproject_roc_config_ResamplerProfile
 * Method:    getRocResamplerHigh
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rocproject_roc_config_ResamplerProfile_getRocResamplerHigh
  (JNIEnv *, jclass);

/*
 * Class:     com_rocproject_roc_config_ResamplerProfile
 * Method:    getRocResamplerMedium
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rocproject_roc_config_ResamplerProfile_getRocResamplerMedium
  (JNIEnv *, jclass);

/*
 * Class:     com_rocproject_roc_config_ResamplerProfile
 * Method:    getRocResamplerLow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rocproject_roc_config_ResamplerProfile_getRocResamplerLow
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
