/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rocproject_roc_address_Address */

#ifndef _Included_com_rocproject_roc_address_Address
#define _Included_com_rocproject_roc_address_Address
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rocproject_roc_address_Address
 * Method:    init
 * Signature: (Lcom/rocproject/roc/address/Family;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_rocproject_roc_address_Address_init
  (JNIEnv *, jobject, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
