/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rocproject_roc_Context */

#ifndef _Included_com_github_rocproject_roc_Context
#define _Included_com_github_rocproject_roc_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rocproject_roc_Context
 * Method:    rocContextOpen
 * Signature: (Lcom/github/rocproject/roc/ContextConfig;)V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Context_rocContextOpen
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_github_rocproject_roc_Context
 * Method:    rocContextClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Context_rocContextClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
