/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rocproject_roc_config_PacketEncoding */

#ifndef _Included_com_rocproject_roc_config_PacketEncoding
#define _Included_com_rocproject_roc_config_PacketEncoding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rocproject_roc_config_PacketEncoding
 * Method:    getRocPacketEncodingAVPL16
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rocproject_roc_config_PacketEncoding_getRocPacketEncodingAVPL16
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
