/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rocproject_roc_receiver_Receiver */

#ifndef _Included_com_rocproject_roc_receiver_Receiver
#define _Included_com_rocproject_roc_receiver_Receiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rocproject_roc_receiver_Receiver
 * Method:    readFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_rocproject_roc_receiver_Receiver_readFloat
  (JNIEnv *, jobject);

/*
 * Class:     com_rocproject_roc_receiver_Receiver
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rocproject_roc_receiver_Receiver_close
  (JNIEnv *, jobject);

/*
 * Class:     com_rocproject_roc_receiver_Receiver
 * Method:    receiverOpen
 * Signature: (Lcom/rocproject/roc/context/Context;Lcom/rocproject/roc/config/ReceiverConfig;)V
 */
JNIEXPORT void JNICALL Java_com_rocproject_roc_receiver_Receiver_receiverOpen
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_rocproject_roc_receiver_Receiver
 * Method:    bind
 * Signature: (IILcom/rocproject/roc/address/Address;)V
 */
JNIEXPORT void JNICALL Java_com_rocproject_roc_receiver_Receiver_bind
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_rocproject_roc_receiver_Receiver
 * Method:    readFloats
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_com_rocproject_roc_receiver_Receiver_readFloats
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
