/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rocproject_roc_PortType */

#ifndef _Included_com_github_rocproject_roc_PortType
#define _Included_com_github_rocproject_roc_PortType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rocproject_roc_PortType
 * Method:    getRocPortAudioSource
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_rocproject_roc_PortType_getRocPortAudioSource
  (JNIEnv *, jclass);

/*
 * Class:     com_github_rocproject_roc_PortType
 * Method:    getRocPortAudioRepair
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_rocproject_roc_PortType_getRocPortAudioRepair
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
