/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rocproject_roc_ChannelSet */

#ifndef _Included_com_github_rocproject_roc_ChannelSet
#define _Included_com_github_rocproject_roc_ChannelSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rocproject_roc_ChannelSet
 * Method:    getRocChannelSetStereo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_rocproject_roc_ChannelSet_getRocChannelSetStereo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
