/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rocproject_roc_FecCode */

#ifndef _Included_com_github_rocproject_roc_FecCode
#define _Included_com_github_rocproject_roc_FecCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rocproject_roc_FecCode
 * Method:    getRocFecCodeDisable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_rocproject_roc_FecCode_getRocFecCodeDisable
  (JNIEnv *, jclass);

/*
 * Class:     com_github_rocproject_roc_FecCode
 * Method:    getRocFecCodeDefault
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_rocproject_roc_FecCode_getRocFecCodeDefault
  (JNIEnv *, jclass);

/*
 * Class:     com_github_rocproject_roc_FecCode
 * Method:    getRocFecCodeRS8M
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_rocproject_roc_FecCode_getRocFecCodeRS8M
  (JNIEnv *, jclass);

/*
 * Class:     com_github_rocproject_roc_FecCode
 * Method:    getRocFecCodeLDPCSTAIRCASE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_rocproject_roc_FecCode_getRocFecCodeLDPCSTAIRCASE
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
