/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rocproject_roc_log_Logger */

#ifndef _Included_com_rocproject_roc_log_Logger
#define _Included_com_rocproject_roc_log_Logger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rocproject_roc_log_Logger
 * Method:    setLevel
 * Signature: (Lcom/rocproject/roc/log/LogLevel;)V
 */
JNIEXPORT void JNICALL Java_com_rocproject_roc_log_Logger_setLevel
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_rocproject_roc_log_Logger
 * Method:    setCallback
 * Signature: (Lcom/rocproject/roc/log/LogHandler;)V
 */
JNIEXPORT void JNICALL Java_com_rocproject_roc_log_Logger_setCallback
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
