/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rocproject_roc_config_ChannelSet */

#ifndef _Included_com_rocproject_roc_config_ChannelSet
#define _Included_com_rocproject_roc_config_ChannelSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rocproject_roc_config_ChannelSet
 * Method:    getRocChannelSetStereo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rocproject_roc_config_ChannelSet_getRocChannelSetStereo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
