/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rocproject_roc_config_FrameEncoding */

#ifndef _Included_com_rocproject_roc_config_FrameEncoding
#define _Included_com_rocproject_roc_config_FrameEncoding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rocproject_roc_config_FrameEncoding
 * Method:    getRocFrameEncodingPCMFloat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rocproject_roc_config_FrameEncoding_getRocFrameEncodingPCMFloat
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
