/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rocproject_roc_Logger */

#ifndef _Included_com_github_rocproject_roc_Logger
#define _Included_com_github_rocproject_roc_Logger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rocproject_roc_Logger
 * Method:    setLevel
 * Signature: (Lcom/github/rocproject/roc/LogLevel;)V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Logger_setLevel
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_github_rocproject_roc_Logger
 * Method:    setCallback
 * Signature: (Lcom/github/rocproject/roc/LogHandler;)V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Logger_setCallback
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
