/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rocproject_roc_Sender */

#ifndef _Included_com_github_rocproject_roc_Sender
#define _Included_com_github_rocproject_roc_Sender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rocproject_roc_Sender
 * Method:    bind
 * Signature: (Lcom/github/rocproject/roc/Address;)V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Sender_bind
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_github_rocproject_roc_Sender
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Sender_close
  (JNIEnv *, jobject);

/*
 * Class:     com_github_rocproject_roc_Sender
 * Method:    senderOpen
 * Signature: (Lcom/github/rocproject/roc/Context;Lcom/github/rocproject/roc/SenderConfig;)V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Sender_senderOpen
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_github_rocproject_roc_Sender
 * Method:    connect
 * Signature: (IILcom/github/rocproject/roc/Address;)V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Sender_connect
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_github_rocproject_roc_Sender
 * Method:    writeFloats
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Sender_writeFloats
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
