/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rocproject_roc_FrameEncoding */

#ifndef _Included_com_github_rocproject_roc_FrameEncoding
#define _Included_com_github_rocproject_roc_FrameEncoding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rocproject_roc_FrameEncoding
 * Method:    getRocFrameEncodingPCMFloat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_rocproject_roc_FrameEncoding_getRocFrameEncodingPCMFloat
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
