/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rocproject_roc_Protocol */

#ifndef _Included_com_github_rocproject_roc_Protocol
#define _Included_com_github_rocproject_roc_Protocol
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rocproject_roc_Protocol
 * Method:    getRocProtoRTP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_rocproject_roc_Protocol_getRocProtoRTP
  (JNIEnv *, jclass);

/*
 * Class:     com_github_rocproject_roc_Protocol
 * Method:    getRocProtoRTPRS8MSOURCE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_rocproject_roc_Protocol_getRocProtoRTPRS8MSOURCE
  (JNIEnv *, jclass);

/*
 * Class:     com_github_rocproject_roc_Protocol
 * Method:    getRocProtoRS8MREPAIR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_rocproject_roc_Protocol_getRocProtoRS8MREPAIR
  (JNIEnv *, jclass);

/*
 * Class:     com_github_rocproject_roc_Protocol
 * Method:    getRocProtoRTPLDPCSOURCE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_rocproject_roc_Protocol_getRocProtoRTPLDPCSOURCE
  (JNIEnv *, jclass);

/*
 * Class:     com_github_rocproject_roc_Protocol
 * Method:    getRocProtoLDPCREPAIR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_rocproject_roc_Protocol_getRocProtoLDPCREPAIR
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
