/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rocproject_roc_Receiver */

#ifndef _Included_com_github_rocproject_roc_Receiver
#define _Included_com_github_rocproject_roc_Receiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rocproject_roc_Receiver
 * Method:    open
 * Signature: (JLcom/github/rocproject/roc/ReceiverConfig;)V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Receiver_open
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_github_rocproject_roc_Receiver
 * Method:    bind
 * Signature: (JIILcom/github/rocproject/roc/Address;)V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Receiver_bind
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     com_github_rocproject_roc_Receiver
 * Method:    readFloats
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Receiver_readFloats
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     com_github_rocproject_roc_Receiver
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Receiver_close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
