/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rocproject_roc_Receiver */

#ifndef _Included_com_github_rocproject_roc_Receiver
#define _Included_com_github_rocproject_roc_Receiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rocproject_roc_Receiver
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Receiver_close
  (JNIEnv *, jobject);

/*
 * Class:     com_github_rocproject_roc_Receiver
 * Method:    receiverOpen
 * Signature: (Lcom/github/rocproject/roc/Context;Lcom/github/rocproject/roc/ReceiverConfig;)V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Receiver_receiverOpen
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_github_rocproject_roc_Receiver
 * Method:    bind
 * Signature: (IILcom/github/rocproject/roc/Address;)V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Receiver_bind
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_github_rocproject_roc_Receiver
 * Method:    readFloats
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Receiver_readFloats
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
