/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rocproject_roc_PacketEncoding */

#ifndef _Included_com_github_rocproject_roc_PacketEncoding
#define _Included_com_github_rocproject_roc_PacketEncoding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rocproject_roc_PacketEncoding
 * Method:    getRocPacketEncodingAVPL16
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_rocproject_roc_PacketEncoding_getRocPacketEncodingAVPL16
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
