/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rocproject_roc_Address */

#ifndef _Included_com_github_rocproject_roc_Address
#define _Included_com_github_rocproject_roc_Address
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rocproject_roc_Address
 * Method:    init
 * Signature: (Lcom/github/rocproject/roc/Family;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_github_rocproject_roc_Address_init
  (JNIEnv *, jobject, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
