/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_Endpoint */

#ifndef _Included_org_rocstreaming_roctoolkit_Endpoint
#define _Included_org_rocstreaming_roctoolkit_Endpoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_Endpoint
 * Method:    getUri
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_rocstreaming_roctoolkit_Endpoint_getUri
  (JNIEnv *, jobject);

/*
 * Class:     org_rocstreaming_roctoolkit_Endpoint
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_Endpoint_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_rocstreaming_roctoolkit_Endpoint
 * Method:    validate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_Endpoint_validate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
