/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_Protocol */

#ifndef _Included_org_rocstreaming_roctoolkit_Protocol
#define _Included_org_rocstreaming_roctoolkit_Protocol
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_Protocol
 * Method:    getRocProtoRTP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_Protocol_getRocProtoRTP
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_Protocol
 * Method:    getRocProtoRTPRS8MSOURCE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_Protocol_getRocProtoRTPRS8MSOURCE
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_Protocol
 * Method:    getRocProtoRS8MREPAIR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_Protocol_getRocProtoRS8MREPAIR
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_Protocol
 * Method:    getRocProtoRTPLDPCSOURCE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_Protocol_getRocProtoRTPLDPCSOURCE
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_Protocol
 * Method:    getRocProtoLDPCREPAIR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_Protocol_getRocProtoLDPCREPAIR
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
