/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_Address */

#ifndef _Included_org_rocstreaming_roctoolkit_Address
#define _Included_org_rocstreaming_roctoolkit_Address
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_Address
 * Method:    init
 * Signature: (Lorg/rocstreaming/roctoolkit/Family;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_Address_init
  (JNIEnv *, jobject, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
