/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_Sender */

#ifndef _Included_org_rocstreaming_roctoolkit_Sender
#define _Included_org_rocstreaming_roctoolkit_Sender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_Sender
 * Method:    open
 * Signature: (JLorg/rocstreaming/roctoolkit/SenderConfig;)J
 */
JNIEXPORT jlong JNICALL Java_org_rocstreaming_roctoolkit_Sender_open
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_rocstreaming_roctoolkit_Sender
 * Method:    bind
 * Signature: (JLorg/rocstreaming/roctoolkit/Address;)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_Sender_bind
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_rocstreaming_roctoolkit_Sender
 * Method:    connect
 * Signature: (JIILorg/rocstreaming/roctoolkit/Address;)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_Sender_connect
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     org_rocstreaming_roctoolkit_Sender
 * Method:    writeFloats
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_Sender_writeFloats
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     org_rocstreaming_roctoolkit_Sender
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_Sender_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
