/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_FrameEncoding */

#ifndef _Included_org_rocstreaming_roctoolkit_FrameEncoding
#define _Included_org_rocstreaming_roctoolkit_FrameEncoding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_FrameEncoding
 * Method:    getRocFrameEncodingPCMFloat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_FrameEncoding_getRocFrameEncodingPCMFloat
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
