/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_LogLevel */

#ifndef _Included_org_rocstreaming_roctoolkit_LogLevel
#define _Included_org_rocstreaming_roctoolkit_LogLevel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_LogLevel
 * Method:    getRocLogNone
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_LogLevel_getRocLogNone
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_LogLevel
 * Method:    getRocLogError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_LogLevel_getRocLogError
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_LogLevel
 * Method:    getRocLogInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_LogLevel_getRocLogInfo
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_LogLevel
 * Method:    getRocLogDebug
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_LogLevel_getRocLogDebug
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_LogLevel
 * Method:    getRocLogTrace
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_LogLevel_getRocLogTrace
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
