/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_ChannelSet */

#ifndef _Included_org_rocstreaming_roctoolkit_ChannelSet
#define _Included_org_rocstreaming_roctoolkit_ChannelSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_ChannelSet
 * Method:    getRocChannelSetStereo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_ChannelSet_getRocChannelSetStereo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
