/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_Context */

#ifndef _Included_org_rocstreaming_roctoolkit_Context
#define _Included_org_rocstreaming_roctoolkit_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_Context
 * Method:    open
 * Signature: (Lorg/rocstreaming/roctoolkit/ContextConfig;)J
 */
JNIEXPORT jlong JNICALL Java_org_rocstreaming_roctoolkit_Context_open
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_rocstreaming_roctoolkit_Context
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_Context_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
