/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_PacketEncoding */

#ifndef _Included_org_rocstreaming_roctoolkit_PacketEncoding
#define _Included_org_rocstreaming_roctoolkit_PacketEncoding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_PacketEncoding
 * Method:    getRocPacketEncodingAVPL16
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_PacketEncoding_getRocPacketEncodingAVPL16
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
