/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_FecCode */

#ifndef _Included_org_rocstreaming_roctoolkit_FecCode
#define _Included_org_rocstreaming_roctoolkit_FecCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_FecCode
 * Method:    getRocFecCodeDisable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_FecCode_getRocFecCodeDisable
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_FecCode
 * Method:    getRocFecCodeDefault
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_FecCode_getRocFecCodeDefault
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_FecCode
 * Method:    getRocFecCodeRS8M
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_FecCode_getRocFecCodeRS8M
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_FecCode
 * Method:    getRocFecCodeLDPCSTAIRCASE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_FecCode_getRocFecCodeLDPCSTAIRCASE
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
