/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_ResamplerProfile */

#ifndef _Included_org_rocstreaming_roctoolkit_ResamplerProfile
#define _Included_org_rocstreaming_roctoolkit_ResamplerProfile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_ResamplerProfile
 * Method:    getRocResamplerDisable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_ResamplerProfile_getRocResamplerDisable
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_ResamplerProfile
 * Method:    getRocResamplerDefault
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_ResamplerProfile_getRocResamplerDefault
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_ResamplerProfile
 * Method:    getRocResamplerHigh
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_ResamplerProfile_getRocResamplerHigh
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_ResamplerProfile
 * Method:    getRocResamplerMedium
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_ResamplerProfile_getRocResamplerMedium
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_ResamplerProfile
 * Method:    getRocResamplerLow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_ResamplerProfile_getRocResamplerLow
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
