/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_PortType */

#ifndef _Included_org_rocstreaming_roctoolkit_PortType
#define _Included_org_rocstreaming_roctoolkit_PortType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_PortType
 * Method:    getRocPortAudioSource
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_PortType_getRocPortAudioSource
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_PortType
 * Method:    getRocPortAudioRepair
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_PortType_getRocPortAudioRepair
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
