/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_Family */

#ifndef _Included_org_rocstreaming_roctoolkit_Family
#define _Included_org_rocstreaming_roctoolkit_Family
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_Family
 * Method:    getRocAFInvalid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_Family_getRocAFInvalid
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_Family
 * Method:    getRocAFAuto
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_Family_getRocAFAuto
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_Family
 * Method:    getRocAFIPv4
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_Family_getRocAFIPv4
  (JNIEnv *, jclass);

/*
 * Class:     org_rocstreaming_roctoolkit_Family
 * Method:    getRocAFIPv6
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_rocstreaming_roctoolkit_Family_getRocAFIPv6
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
