/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_RocSender */

#ifndef _Included_org_rocstreaming_roctoolkit_RocSender
#define _Included_org_rocstreaming_roctoolkit_RocSender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_RocSender
 * Method:    nativeOpen
 * Signature: (JLorg/rocstreaming/roctoolkit/RocSenderConfig;)J
 */
JNIEXPORT jlong JNICALL Java_org_rocstreaming_roctoolkit_RocSender_nativeOpen
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_rocstreaming_roctoolkit_RocSender
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_RocSender_nativeClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocstreaming_roctoolkit_RocSender
 * Method:    nativeConfigure
 * Signature: (JIILorg/rocstreaming/roctoolkit/InterfaceConfig;)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_RocSender_nativeConfigure
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     org_rocstreaming_roctoolkit_RocSender
 * Method:    nativeConnect
 * Signature: (JIILorg/rocstreaming/roctoolkit/Endpoint;)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_RocSender_nativeConnect
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     org_rocstreaming_roctoolkit_RocSender
 * Method:    nativeUnlink
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_RocSender_nativeUnlink
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_rocstreaming_roctoolkit_RocSender
 * Method:    nativeWriteFloats
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_RocSender_nativeWriteFloats
  (JNIEnv *, jobject, jlong, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
