/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_RocReceiver */

#ifndef _Included_org_rocstreaming_roctoolkit_RocReceiver
#define _Included_org_rocstreaming_roctoolkit_RocReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_RocReceiver
 * Method:    open
 * Signature: (JLorg/rocstreaming/roctoolkit/RocReceiverConfig;)J
 */
JNIEXPORT jlong JNICALL Java_org_rocstreaming_roctoolkit_RocReceiver_open
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_rocstreaming_roctoolkit_RocReceiver
 * Method:    setMulticastGroup
 * Signature: (JIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_RocReceiver_setMulticastGroup
  (JNIEnv *, jobject, jlong, jint, jint, jstring);

/*
 * Class:     org_rocstreaming_roctoolkit_RocReceiver
 * Method:    bind
 * Signature: (JIILorg/rocstreaming/roctoolkit/Endpoint;)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_RocReceiver_bind
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     org_rocstreaming_roctoolkit_RocReceiver
 * Method:    readFloats
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_RocReceiver_readFloats
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     org_rocstreaming_roctoolkit_RocReceiver
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_RocReceiver_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
