/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_RocContext */

#ifndef _Included_org_rocstreaming_roctoolkit_RocContext
#define _Included_org_rocstreaming_roctoolkit_RocContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_RocContext
 * Method:    nativeOpen
 * Signature: (Lorg/rocstreaming/roctoolkit/RocContextConfig;)J
 */
JNIEXPORT jlong JNICALL Java_org_rocstreaming_roctoolkit_RocContext_nativeOpen
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_rocstreaming_roctoolkit_RocContext
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_RocContext_nativeClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocstreaming_roctoolkit_RocContext
 * Method:    nativeRegisterEncoding
 * Signature: (JILorg/rocstreaming/roctoolkit/MediaEncoding;)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_RocContext_nativeRegisterEncoding
  (JNIEnv *, jclass, jlong, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
