/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_Logger */

#ifndef _Included_org_rocstreaming_roctoolkit_Logger
#define _Included_org_rocstreaming_roctoolkit_Logger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_Logger
 * Method:    setLevel
 * Signature: (Lorg/rocstreaming/roctoolkit/LogLevel;)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_Logger_setLevel
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_rocstreaming_roctoolkit_Logger
 * Method:    setCallback
 * Signature: (Lorg/rocstreaming/roctoolkit/LogHandler;)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_Logger_setCallback
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
