/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_RocLogger */

#ifndef _Included_org_rocstreaming_roctoolkit_RocLogger
#define _Included_org_rocstreaming_roctoolkit_RocLogger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_RocLogger
 * Method:    setLevel
 * Signature: (Lorg/rocstreaming/roctoolkit/RocLogLevel;)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_RocLogger_setLevel
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_rocstreaming_roctoolkit_RocLogger
 * Method:    setHandler
 * Signature: (Lorg/rocstreaming/roctoolkit/RocLogHandler;)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_RocLogger_setHandler
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
