/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocstreaming_roctoolkit_RocContext */

#ifndef _Included_org_rocstreaming_roctoolkit_RocContext
#define _Included_org_rocstreaming_roctoolkit_RocContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocstreaming_roctoolkit_RocContext
 * Method:    open
 * Signature: (Lorg/rocstreaming/roctoolkit/RocContextConfig;)J
 */
JNIEXPORT jlong JNICALL Java_org_rocstreaming_roctoolkit_RocContext_open
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_rocstreaming_roctoolkit_RocContext
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocstreaming_roctoolkit_RocContext_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
