// Code generated by bindgen.py from roc-streaming/bindgen
// roc-toolkit git tag: v0.4.0-62-g60db91cb, commit: 60db91cb

package org.rocstreaming.roctoolkit;

/**
 * Channel layout.
 * <p>
 * Defines number of channels and meaning of each channel.
 */
public enum ChannelLayout {

    /**
     * Multi-track audio.
     * <p>
     * In multitrack layout, stream contains multiple channels which represent independent
     * "tracks" without any special meaning (unlike stereo or surround) and hence without any
     * special processing or mapping.
     * <p>
     * The number of channels is arbitrary and is defined by {@code tracks} field of
     * {@link MediaEncoding} struct.
     */
    MULTITRACK(1),

    /**
     * Mono.
     * <p>
     * One channel with monophonic sound.
     */
    MONO(2),

    /**
     * Stereo.
     * <p>
     * Two channels: left, right.
     */
    STEREO(3),
    ;

    final int value;

    ChannelLayout(int value) {
        this.value = value;
    }
}
