// Code generated by generate_enums script from roc-toolkit; DO NOT EDIT!

package org.rocstreaming.roctoolkit;

/**
 * Channel set.
 */
public enum ChannelSet {

    /**
     * Stereo.
     * <p>
     * Two channels: left and right.
     */
    STEREO(0x3),
    ;

    final int value;

    ChannelSet(int value) {
        this.value = value;
    }
}
