// DO NOT EDIT! Code generated by generate_enums script from roc-toolkit
// roc-toolkit git tag: v0.2.5-11-g14d642e9, commit: 14d642e9

package org.rocstreaming.roctoolkit;

/**
 * Channel set.
 */
public enum ChannelSet {

    /**
     * Stereo.
     * <p>
     * Two channels: left and right.
     */
    STEREO(0x3),
    ;

    final int value;

    ChannelSet(int value) {
        this.value = value;
    }
}
