// Code generated by bindgen.py from roc-streaming/bindgen
// roc-toolkit git tag: v0.4.0-62-g60db91cb, commit: 60db91cb

package org.rocstreaming.roctoolkit;

/**
 * Latency tuner profile.
 * <p>
 * Defines whether latency tuning is enabled and which algorithm is used.
 */
public enum LatencyTunerProfile {

    /**
     * Default profile.
     * <p>
     * On receiver, when {@link LatencyTunerBackend#NIQ} is used, selects
     * {@link LatencyTunerProfile#RESPONSIVE} if target latency is low, and
     * {@link LatencyTunerProfile#GRADUAL} if target latency is high.
     * <p>
     * On sender, selects {@link LatencyTunerProfile#INTACT}.
     */
    DEFAULT(0),

    /**
     * No latency tuning.
     * <p>
     * In this mode, clock speed is not adjusted. Default on sender.
     * <p>
     * You can set this mode on receiver, and set some other mode on sender, to do latency
     * tuning on sender side instead of recever side. It's useful when receiver is
     * CPU-constrained and sender is not, because latency tuner relies on resampling, which
     * is CPU-demanding.
     * <p>
     * You can also set this mode on both sender and receiver if you don't need latency
     * tuning at all. However, if sender and receiver have independent clocks (which is
     * typically the case), clock drift will lead to periodic playback disruptions caused by
     * underruns and overruns.
     */
    INTACT(1),

    /**
     * Responsive latency tuning.
     * <p>
     * Clock speed is adjusted quickly and accurately.
     * <p>
     * Requires high precision clock adjustment, hence recommended for use with
     * {@link ResamplerBackend#BUILTIN}.
     * <p>
     * Pros:
     * <ul>
     *   <li>allows very low latency and synchronization error</li>
     * </ul>
     * <p>
     * Cons:
     * <ul>
     *   <li>does not work well with some resampler backends</li>
     *   <li>does not work well with {@link LatencyTunerBackend#NIQ} if network jitter is high</li>
     * </ul>
     */
    RESPONSIVE(2),

    /**
     * Gradual latency tuning.
     * <p>
     * Clock speed is adjusted slowly and smoothly.
     * <p>
     * Pros:
     * <ul>
     *   <li>works well even with high network jitter</li>
     *   <li>works well with any resampler backend</li>
     * </ul>
     * <p>
     * Cons:
     * <ul>
     *   <li>does not allow very low latency and synchronization error</li>
     * </ul>
     */
    GRADUAL(3),
    ;

    final int value;

    LatencyTunerProfile(int value) {
        this.value = value;
    }
}
