// Code generated by bindgen.py from roc-streaming/bindgen
// roc-toolkit git tag: v0.4.0-62-g60db91cb, commit: 60db91cb

package org.rocstreaming.roctoolkit;

/**
 * Latency tuner backend.
 * <p>
 * Defines which latency is monitored and tuned by latency tuner.
 */
public enum LatencyTunerBackend {

    /**
     * Default backend.
     * <p>
     * Current default is {@link LatencyTunerBackend#NIQ}.
     */
    DEFAULT(0),

    /**
     * Latency tuning is based on network incoming queue length.
     * <p>
     * In this mode, latency is defined as incoming queue length (in nanoseconds). Latency
     * tuner monitors queue length and and adjusts playback clock speed to keep queue length
     * close to configured target latency.
     * <p>
     * Keeping constant queue length allows to match playback clock speed with the capture
     * clock speed and to keep the overall latency constant (yet unknown).
     * <p>
     * On receiver, this backend is always available, without any protocol help. On sender,
     * this backend works only if RTCP is enabled and both sender and receiver are
     * implemented with roc-toolkit, as it relies on a non-standard RTCP extension to report
     * receiver queue length to sender.
     * <p>
     * Pros:
     * <ul>
     *   <li>works with any protocol if used on receiver (does not require RTCP or NTP)</li>
     * </ul>
     * <p>
     * Cons:
     * <ul>
     *   <li>synchronizes only clock speed, but not position; different receivers will have different
     *       (constant) delays</li>
     *   <li>affected by network jitter; spikes in packet delivery will cause slow oscillations in
     *       clock speed</li>
     * </ul>
     */
    NIQ(2),
    ;

    final int value;

    LatencyTunerBackend(int value) {
        this.value = value;
    }
}
