// Code generated by bindgen.py from roc-streaming/bindgen
// roc-toolkit git tag: v0.3.0, commit: 57b932b8

package org.rocstreaming.roctoolkit;

import java.time.Duration;
import lombok.*;

/**
 * Media encoding.
 * <p>
 * Defines format and parameters of samples encoded in frames or packets.
 */
@Getter
@Builder(builderClassName = "Builder", toBuilder = true)
@ToString
@EqualsAndHashCode
public class MediaEncoding {

    /**
     * Sample frequency.
     * <p>
     * Defines number of samples per channel per second (e.g. 44100).
     */
    private int rate;

    /**
     * Sample format.
     * <p>
     * Defines sample precision and encoding.
     */
    private Format format;

    /**
     * Channel layout.
     * <p>
     * Defines number of channels and meaning of each channel.
     */
    private ChannelLayout channels;

    /**
     * Multi-track channel count.
     * <p>
     * If {@code channels} is {@link ChannelLayout#MULTITRACK}, defines number of channels
     * (which represent independent "tracks"). For other channel layouts should be zero.
     * <p>
     * Should be in range [1; 1024].
     */
    private int tracks;

    /**
     * Construct builder for {@link MediaEncoding}.
     */
    public static MediaEncoding.Builder builder() {
        return new MediaEncodingValidator();
    }
}
