// DO NOT EDIT! Code generated by generate_enums script from roc-toolkit
// roc-toolkit git tag: v0.2.5-11-g14d642e9, commit: 14d642e9

package org.rocstreaming.roctoolkit;

/**
 * Packet encoding.
 */
public enum PacketEncoding {

    /**
     * PCM signed 16-bit.
     * <p>
     * "L16" encoding from RTP A/V Profile (RFC 3551). Uncompressed samples
     * coded as interleaved 16-bit signed big-endian integers in two's
     * complement notation.
     */
    AVP_L16(2),
    ;

    final int value;

    PacketEncoding(int value) {
        this.value = value;
    }
}
