// Code generated by generate_enums script from roc-toolkit; DO NOT EDIT!

package org.rocstreaming.roctoolkit;

/**
 * Network protocol.
 * <p>
 * Defines URI scheme of {@link Endpoint}.
 */
public enum Protocol {

    /**
     * RTSP 1.0 (RFC 2326) or RTSP 2.0 (RFC 7826).
     * <p>
     * Interfaces: <ul>
     * <li>{@link Interface#CONSOLIDATED}</li>
     * </ul>
     * <p>
     * Transports: <ul>
     * <li>for signaling: TCP</li>
     * <li>for media: RTP and RTCP over UDP or TCP</li>
     * </ul>
     */
    RTSP(10),

    /**
     * RTP over UDP (RFC 3550).
     * <p>
     * Interfaces: <ul>
     * <li>{@link Interface#AUDIO_SOURCE}</li>
     * </ul>
     * <p>
     * Transports: <ul>
     * <li>UDP</li>
     * </ul>
     * <p>
     * Audio encodings: <ul>
     * <li>{@link PacketEncoding#AVP_L16}</li>
     * </ul>
     * <p>
     * FEC encodings: <ul>
     * <li>none</li>
     * </ul>
     */
    RTP(20),

    /**
     * RTP source packet (RFC 3550) + FECFRAME Reed-Solomon footer (RFC 6865)
     * with m=8.
     * <p>
     * Interfaces: <ul>
     * <li>{@link Interface#AUDIO_SOURCE}</li>
     * </ul>
     * <p>
     * Transports: <ul>
     * <li>UDP</li>
     * </ul>
     * <p>
     * Audio encodings: <ul>
     * <li>similar to {@link Protocol#RTP}</li>
     * </ul>
     * <p>
     * FEC encodings: <ul>
     * <li>{@link FecEncoding#RS8M}</li>
     * </ul>
     */
    RTP_RS8M_SOURCE(30),

    /**
     * FEC repair packet + FECFRAME Reed-Solomon header (RFC 6865) with m=8.
     * <p>
     * Interfaces: <ul>
     * <li>{@link Interface#AUDIO_REPAIR}</li>
     * </ul>
     * <p>
     * Transports: <ul>
     * <li>UDP</li>
     * </ul>
     * <p>
     * FEC encodings: <ul>
     * <li>{@link FecEncoding#RS8M}</li>
     * </ul>
     */
    RS8M_REPAIR(31),

    /**
     * RTP source packet (RFC 3550) + FECFRAME LDPC-Staircase footer (RFC 6816).
     * <p>
     * Interfaces: <ul>
     * <li>{@link Interface#AUDIO_SOURCE}</li>
     * </ul>
     * <p>
     * Transports: <ul>
     * <li>UDP</li>
     * </ul>
     * <p>
     * Audio encodings: <ul>
     * <li>similar to {@link Protocol#RTP}</li>
     * </ul>
     * <p>
     * FEC encodings: <ul>
     * <li>{@link FecEncoding#LDPC_STAIRCASE}</li>
     * </ul>
     */
    RTP_LDPC_SOURCE(32),

    /**
     * FEC repair packet + FECFRAME LDPC-Staircase header (RFC 6816).
     * <p>
     * Interfaces: <ul>
     * <li>{@link Interface#AUDIO_REPAIR}</li>
     * </ul>
     * <p>
     * Transports: <ul>
     * <li>UDP</li>
     * </ul>
     * <p>
     * FEC encodings: <ul>
     * <li>{@link FecEncoding#LDPC_STAIRCASE}</li>
     * </ul>
     */
    LDPC_REPAIR(33),

    /**
     * RTCP over UDP (RFC 3550).
     * <p>
     * Interfaces: <ul>
     * <li>{@link Interface#AUDIO_CONTROL}</li>
     * </ul>
     * <p>
     * Transports: <ul>
     * <li>UDP</li>
     * </ul>
     */
    RTCP(70),
    ;

    final int value;

    Protocol(int value) {
        this.value = value;
    }
}
