// Code generated by bindgen.py from roc-streaming/bindgen
// roc-toolkit git tag: v0.3.0, commit: 57b932b8

package org.rocstreaming.roctoolkit;

/**
 * Resampler profile.
 * <p>
 * Affects CPU usage and quality. Each resampler backend treats profile in its own way.
 */
public enum ResamplerProfile {

    /**
     * Default profile.
     * <p>
     * Current default is {@link ResamplerProfile#MEDIUM}.
     */
    DEFAULT(0),

    /**
     * High quality, higher CPU usage.
     */
    HIGH(1),

    /**
     * Medium quality, medium CPU usage.
     */
    MEDIUM(2),

    /**
     * Low quality, lower CPU usage.
     */
    LOW(3),
    ;

    final int value;

    ResamplerProfile(int value) {
        this.value = value;
    }
}
