// DO NOT EDIT! Code generated by generate_enums script from roc-toolkit
// roc-toolkit git tag: v0.2.5-11-g14d642e9, commit: 14d642e9

package org.rocstreaming.roctoolkit;

/**
 * Resampler backend.
 * <p>
 * Affects speed and quality. Some backends may be disabled at build time.
 */
public enum ResamplerBackend {

    /**
     * Default backend.
     * <p>
     * Depends on what was enabled at build time.
     */
    DEFAULT(0),

    /**
     * Slow built-in resampler.
     * <p>
     * Always available.
     */
    BUILTIN(1),

    /**
     * Fast good-quality resampler from SpeexDSP.
     * <p>
     * May be disabled at build time.
     */
    SPEEX(2),
    ;

    final int value;

    ResamplerBackend(int value) {
        this.value = value;
    }
}
