// Code generated by bindgen.py from roc-streaming/bindgen
// roc-toolkit git tag: v0.3.0, commit: 57b932b8

package org.rocstreaming.roctoolkit;

import java.time.Duration;
import lombok.*;

/**
 * Context configuration.
 * <p>
 * RocContextConfig object can be instantiated with {@link RocContextConfig#builder()}.
 *
 * @see RocContext
 */
@Getter
@Builder(builderClassName = "Builder", toBuilder = true)
@ToString
@EqualsAndHashCode
public class RocContextConfig {

    /**
     * Maximum size in bytes of a network packet.
     * <p>
     * Defines the amount of bytes allocated per network packet. Sender and receiver won't
     * handle packets larger than this. If zero, default value is used.
     */
    private int maxPacketSize;

    /**
     * Maximum size in bytes of an audio frame.
     * <p>
     * Defines the amount of bytes allocated per intermediate internal frame in the pipeline.
     * Does not limit the size of the frames provided by user. If zero, default value is
     * used.
     */
    private int maxFrameSize;

    /**
     * Construct lombok builder for {@link RocContextConfig}.
     */
    public static RocContextConfig.Builder builder() {
        return new RocContextConfigValidator();
    }
}
